# Local development configuration for go-angular-boilerplate

service:
  host: "localhost"
  port: 8080
  read_timeout: 10 # seconds
  write_timeout: 10 # seconds

database:
  uri: "mongodb://localhost:27017"
  database: "boilerplate"
  # username: "admin"  # optional, uncomment if using authentication
  # password: "password"  # optional, uncomment if using authentication
  timeout: 10 # seconds

auth:
  enabled: true # Set to true to enable Keycloak authentication
  issuer: "http://localhost:8081/realms/boilerplate"
  client_id: "boilerplate-client"
  client_secret: "ikF8yNEKjsa55QBY2nqGMiAKl1Ygvn0f" # Set via environment variable for security
  jwks_url: "http://localhost:8081/realms/boilerplate/protocol/openid-connect/certs"

logging:
  level: "info" # debug, info, warn, error
  format: "console" # console, json
  # Uncomment to enable Loki logging
  # loki:
  #   url: "http://localhost:3100"
  #   bearer_token: ""  # Optional bearer token for Loki

cors:
  allowed_origins:
    - "*" # Allow all origins by default, specify origins like ["http://localhost:4200"] for production
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  exposed_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 3600 # seconds

docs:
  enabled: true # Set to false in production for security (hides API documentation)
